name = "ArmaForces - JBAD Buildings Fix"
modname = "armaforces_jbad_buildings_fix"
prefix = "armaforces"
author = "ArmaForces, veteran29"
version = "1.0.0"
files = ["mod.cpp"]

exclude = ["*.psd", "*.png", "*.tga"]

keyname = "{{prefix}}_jbad_buildings_fix_{{version}}"
signame = "{{prefix}}_jbad_buildings_fix_{{version}}"
reuse_private_key = true

releasebuild = [
    "!Set_version",
    "@zip",
    "!publish"
]

[scripts]
    [scripts.Set_version]
        steps_windows = [
            "powershell ./tools/Set-Version.ps1 {{version}} '@armaforces_jbad_buildings_fix'"
        ]
        # show_output = true

    [scripts.publish]
        steps_windows = [
            "powershell ./tools/Publish.ps1 {{version}} YOUR_WORKSHOP_ID '@armaforces_jbad_buildings_fix'"
        ]
        show_output = true
